version: '3.8'
services:
    sqlserver:
        image: "mcr.microsoft.com/mssql/server:latest"
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "pa55w0rd!"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"